package com.iyeeku.demo;

import com.iyeeku.util.AutoGenerateUtil;
import com.iyeeku.util.CompressFileGZIP;
import com.iyeeku.util.FileUtil;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;

/**
 * @ClassName AutoGenerateDataFile
 * @Description TODO
 * @Author YangQuan
 * @Date 2019/9/25 20:13
 * @Version 1.0
 **/
public class AutoGenerateDataFile {

    private final static Logger LOGGER = LoggerFactory.getLogger(AutoGenerateDataFile.class);

    public final static String FILE_PREFIX = "IYEEKU_TEST_HX_JYWLXXWJ";
    public final static String LOCAL_DATA_DIR = "/home/iyeekuftpdata/in/";
    public final static String HDFS_BASE_DIR = "/in/data" + FILE_PREFIX + "/";
    public final static String LOG_FILE = "/home/shell/logs/autoGenerateDataFile.log";

    public static void main(String[] args) {
        LOGGER.info("开始生成数据...");
        SimpleDateFormat df = new SimpleDateFormat("yyyyMMdd");
        String dataDate = df.format(new Date());
        String millis = String.valueOf(System.currentTimeMillis());

        millis = "000000.000000";

        String dataFileName = FILE_PREFIX + "." + dataDate + "." + millis + ".dat";
        String flgFileName = FILE_PREFIX + "." + dataDate + "." + millis + ".flg";
        String dataFileOutPath = LOCAL_DATA_DIR + dataDate + "/" + dataFileName;
        String flgFileOutPath = LOCAL_DATA_DIR + dataDate + "/" + flgFileName;

        FileUtil.mkdir(LOCAL_DATA_DIR + dataDate);

        int maxRow = 100;
        Random random = new Random();
        int randomTotal = random.nextInt(maxRow) + maxRow;

        File fout = null;
        FileOutputStream fos = null;
        BufferedWriter bw = null;

        try {
            fout = new File(dataFileOutPath);
            fos = new FileOutputStream(fout);
            bw = new BufferedWriter(new OutputStreamWriter(fos));
            for (int i = 0 ; i < randomTotal ; i++){
                StringBuffer sb = new StringBuffer();
                sb.append("H00100").append(dataDate).append(String.valueOf(System.currentTimeMillis()).substring(7)).append(AutoGenerateUtil.formatCompWithZore(i,10))
                        .append("11")
                        //jyjgbh   CHAR(3)
                        .append("701")
                        //gylsh CHAR(8)
                        .append(AutoGenerateUtil.formatCompWithZore(random.nextInt(99999999),8))
                        //zhdh  CHAR(18)
                        .append("117010100100446448")
                        //dfzh   CHAR(32)
                        .append("XDF01010010044644800000000000000")
                        //wlzhmc VARCHAR(120)
                        .append(String.format("%1$-120s" , "test_wlzhmc_name_" + String.format("%0" + 12 + "d" , random.nextInt(999999999))))
                        //xzfdfhh CHAR(14)
                        .append("G10" + String.format("%0" + 11 + "d" , random.nextInt(999999999)))
                        //wzfdfhm varchar(70)
                        .append(String.format("%1$-70s","test_wzfdfhm_name_" + String.format("%0" + 10 + "d" , random.nextInt(999999999))))
                        //jyje 17
                        .append(String.format("% " + 14 + "d" , random.nextInt(999999999)) + "." + String.format("%0" + 2 + "d" , random.nextInt(99)))
                        // bbjyje 17
                        .append(String.format("% " + 14 + "d" , random.nextInt(999999999)) + "." + String.format("%0" + 2 + "d" , random.nextInt(99)))
                        //xzbz CHAR(1)
                        .append("1")
                        //szbj CHAR(1)
                        .append("1")
                        //zydh CHAR(3)
                        .append("120")
                        //jlzt CHAR(1)
                        .append("1")
                        //cpzxh INTEGER(12)
                        .append(String.format("%0" + 12 + "d",random.nextInt(999999999)))
                        //cpznxh  INTEGER(12)
                        .append(String.format("%0" + 12 + "d",random.nextInt(999999999)))
                        //khdh CHAR(10)
                        .append(AutoGenerateUtil.getRandomKhbh())
                        //cpdh CHAR(9)
                        .append(String.format("%1$-9s" ,"a"))
                        // hbzl CHAR(2)
                        .append("01")
                        //jyrq  CHAR(8)
                        .append(dataDate);
                bw.write(sb.toString());
                bw.newLine();
            }
        }catch (Exception e){
            e.printStackTrace();
           LOGGER.error("数据文件生产失败",e);
        }finally {
            try {
                if (bw != null){
                    bw.close();
                }
                if (fos != null){
                    fos.close();
                }
            } catch (IOException e){
                LOGGER.error("Close stream error", e);
            }
        }


        //压缩为.gz文件
        CompressFileGZIP.doCompressFile(dataFileOutPath);
        //删除dat文件
        FileUtil.deleteFile(dataFileOutPath);

        //生成flg文件
        String createFlgTime = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
        StringBuffer flgBuff = new StringBuffer();
        flgBuff.append(dataFileName).append(" 391 1").append(createFlgTime).append("\n\n")
                .append("FILENAME=").append(dataFileName).append(".gz\n\n")
                .append("FILESIZE=").append(FileUtil.getFileSize(dataFileOutPath + ".gz")).append("\n\n")
                .append("ROWCOUNT=").append(randomTotal).append("\n\n")
                .append("CREATEDATETIME=").append(createFlgTime).append("\n\n")
                .append("SQL=select hxjylsbh,jydqdh,gylsh\n\n")
                .append("ROWLENGTH=390\n\n")
                .append("COLUMNCOUNT=21\n\n")
                .append("COLUMNDESCRIPTION=\n")
                .append("1$$hxjylsbh$$char(30)$$(1,30)\n")
                .append("2$$jydqdh$$char(2)$$(31,32)\n")
                .append("3$$jyjgdh$$char(3)$$(33,35)\n")
                .append("4$$gylsh$$char(8)$$(36,43)\n")
                .append("5$$zhdh$$char(8)$$(44,61)\n")
                .append("6$$dfzh$$char(32)$$(62,93)\n")
                .append("7$$wlzhmc$$varchar(120)$$(94,213)\n")
                .append("8$$xzfdfhh$$char(14)$$(214,227)\n")
                .append("9$$xzfdfhm$$varchar(70)$$(228,297)\n")
                .append("10$$jyje$$decimal(15,2)$$(298,314)\n")
                .append("11$$bbjyje$$decimal(15,2)$$(315,331)\n")
                .append("12$$xzbz$$char(1)$$(332,332)\n")
                .append("13$$szbj$$char(1)$$(333,333)\n")
                .append("14$$zydh$$char(3)$$(334,336)\n")
                .append("15$$jlzt$$char(1)$$(337,337)\n")
                .append("16$$cpzxh$$int$$(338,349)\n")
                .append("17$$cpznxh$$int$$(350,361)\n")
                .append("18$$khdh$$char(10)$$(362,371)\n")
                .append("19$$cpdh$$char(9)$$(372,380)\n")
                .append("20$$hbzl$$char(2)$$(381,382)\n")
                .append("21$$jyrq$$char(10)$$(383,390)\n\n\n\n");

        FileUtil.write(flgFileOutPath,flgBuff);


    }



}
